name: Cush Comfort
favicon: null
layout_spectrum: 0.6309361420571804
typography_spectrum: 0.8355788716580719
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5239125511143357
  lightness: 0.33659824449568987
  saturation: 0.9272475109901279
  rhythmicContrast: 0.3396737761795521
purpose: []
